packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  "@types/node": ^22.13.14
  hono: ^4.8.2
  "@trpc/server": ^11.7.2
  better-auth: ^1.4.18
  ai: ^6.0.3
  "@trpc/client": ^11.7.2
